# Generated by Django 4.1.1 on 2022-09-29 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Blog',
        ),
        migrations.RenameModel(
            old_name='Certificates',
            new_name='Certificate',
        ),
    ]
