# Generated by Django 4.1.1 on 2022-09-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_blogs_blog_rename_certificates_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='picture_link',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
