# Generated by Django 4.1.1 on 2022-10-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_qanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='languages',
            field=models.JSONField(default={'none': 'none'}),
            preserve_default=False,
        ),
    ]
