# Generated by Django 4.1.1 on 2022-10-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_skill_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='url',
            field=models.CharField(default='url', max_length=100),
            preserve_default=False,
        ),
    ]
